#spring.devtools.restart.enabled=true
#
#spring.devtools.restart.additional-paths=src/main/java
#
#spring.devtools.restart.exclude=static/**

server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/websql
    username: root
    password: 3.14159fjh
